# Generated by Django 5.2.4 on 2025-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_full_name', models.CharField(max_length=255, verbose_name='ФИО отправителя')),
                ('recipient_full_name', models.CharField(max_length=255, verbose_name='ФИО получателя')),
                ('origin_location', models.CharField(max_length=255, verbose_name='Пункт отправки')),
                ('destination_location', models.CharField(max_length=255, verbose_name='Пункт получения')),
                ('origin_postcode', models.IntegerField(verbose_name='Индекс места отправки')),
                ('destination_postcode', models.IntegerField(verbose_name='Индекс места получения')),
                ('letter_type', models.IntegerField(choices=[(1, 'письмо'), (2, 'заказное письмо'), (3, 'ценное письмо'), (4, 'экспресс-письмо')], default=1, verbose_name='Тип письма')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Вес письма (кг)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_full_name', models.CharField(max_length=255, verbose_name='ФИО отправителя')),
                ('recipient_full_name', models.CharField(max_length=255, verbose_name='ФИО получателя')),
                ('origin_location', models.CharField(max_length=255, verbose_name='Пункт отправки')),
                ('destination_location', models.CharField(max_length=255, verbose_name='Пункт получения')),
                ('origin_postcode', models.IntegerField(verbose_name='Индекс места отправки')),
                ('destination_postcode', models.IntegerField(verbose_name='Индекс места получения')),
                ('notification_phone', models.CharField(max_length=20, verbose_name='Телефон для извещения')),
                ('parcel_type', models.IntegerField(choices=[(1, 'мелкий пакет'), (2, 'посылка'), (3, 'посылка 1 класса'), (4, 'ценная посылка'), (5, 'посылка международная'), (6, 'экспресс-посылка')], default=2, verbose_name='Тип посылки')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
