# Generated by Django 5.2.4 on 2025-08-11 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'письмо'), (2, 'заказное письмо'), (3, 'ценное письмо'), (4, 'экспресс-письмо')], default=1, verbose_name='Тип письма'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'мелкий пакет'), (2, 'посылка'), (3, 'посылка 1 класса'), (4, 'ценная посылка'), (5, 'посылка международная'), (6, 'экспресс-посылка')], default=2, verbose_name='Тип посылки'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['origin_postcode'], name='parcels_let_origin__375c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['destination_postcode'], name='parcels_let_destina_ebe156_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['origin_postcode'], name='parcels_par_origin__dcd1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['destination_postcode'], name='parcels_par_destina_7fc598_idx'),
        ),
    ]
